package fleetProject;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Registeruser generated by hbm2java
 */
@Entity
@Table(name = "registeruser", catalog = "fleetmanagement")
public class Registeruser implements java.io.Serializable {

	private Integer userId;
	private String userPassword;
	private String userFirstname;
	private String userLastname;
	private String userAddress;
	private String userEmailId;
	private String userDrivingLicenseNo;
	private int userPassportNo;
	private String userPhoneNo;
	private String userAadharNo;
	private String userDob;

	public Registeruser() {
	}

	public Registeruser(String userPassword, String userFirstname, String userLastname, String userAddress,
			String userEmailId, String userDrivingLicenseNo, int userPassportNo, String userPhoneNo,
			String userAadharNo, String userDob) {
		this.userPassword = userPassword;
		this.userFirstname = userFirstname;
		this.userLastname = userLastname;
		this.userAddress = userAddress;
		this.userEmailId = userEmailId;
		this.userDrivingLicenseNo = userDrivingLicenseNo;
		this.userPassportNo = userPassportNo;
		this.userPhoneNo = userPhoneNo;
		this.userAadharNo = userAadharNo;
		this.userDob = userDob;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_password", nullable = false, length = 256)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_firstname", nullable = false, length = 256)
	public String getUserFirstname() {
		return this.userFirstname;
	}

	public void setUserFirstname(String userFirstname) {
		this.userFirstname = userFirstname;
	}

	@Column(name = "user_lastname", nullable = false, length = 256)
	public String getUserLastname() {
		return this.userLastname;
	}

	public void setUserLastname(String userLastname) {
		this.userLastname = userLastname;
	}

	@Column(name = "user_address", nullable = false, length = 256)
	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	@Column(name = "user_email_id", nullable = false, length = 256)
	public String getUserEmailId() {
		return this.userEmailId;
	}

	public void setUserEmailId(String userEmailId) {
		this.userEmailId = userEmailId;
	}

	@Column(name = "user_driving_license_no", nullable = false, length = 256)
	public String getUserDrivingLicenseNo() {
		return this.userDrivingLicenseNo;
	}

	public void setUserDrivingLicenseNo(String userDrivingLicenseNo) {
		this.userDrivingLicenseNo = userDrivingLicenseNo;
	}

	@Column(name = "user_passport_no", nullable = false)
	public int getUserPassportNo() {
		return this.userPassportNo;
	}

	public void setUserPassportNo(int userPassportNo) {
		this.userPassportNo = userPassportNo;
	}

	@Column(name = "user_phone_no", nullable = false, length = 11)
	public String getUserPhoneNo() {
		return this.userPhoneNo;
	}

	public void setUserPhoneNo(String userPhoneNo) {
		this.userPhoneNo = userPhoneNo;
	}

	@Column(name = "user_aadhar_no", nullable = false, length = 256)
	public String getUserAadharNo() {
		return this.userAadharNo;
	}

	public void setUserAadharNo(String userAadharNo) {
		this.userAadharNo = userAadharNo;
	}

	@Column(name = "user_dob", nullable = false, length = 10)
	public String getUserDob() {
		return this.userDob;
	}

	public void setUserDob(String userDob) {
		this.userDob = userDob;
	}

}
